apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  docker-server: docker.io
  docker-username: {{.Values.Username}}
  docker-password: {{.Values.Password}}
  docker-email: {{.Values.Email}}